= CUD File Format Strategy

The CUD file format is a JSON file that represents operations (**C**reate, **U**pdate, **D**elete) performed on nodes or relationships.

== Configuration

You can configure the topic in the following way:

[source,json,subs="verbatim,attributes"]
----
"neo4j.cud.topics": "<COMMA_SEPARATED_LIST_OF_TOPICS>"
----

For instance, if you have two topics, `topic.1` and `topic.2` that you publish as CUD-formatted messages, you can configure the sink instance as follows.

[source,json]
----
"neo4j.cud.topics": "topic.1,topic.2"
----

== Creating Sink instance

:strategy: cud
include::partial$create-sink-instance.adoc[]

== CUD Format Specification

We have two formats:

* `Node`
* `Relationship`

=== Node

The Node format defines a set of fields which describes the operation (`create`, `update`, `merge` and `delete`), label and properties of a node entity.

[#table_cud_node_fields]
.**Node format** fields
[cols="1,2,3",opts=header]
|===

| Field
| Mandatory
| Description

| op
| label:Mandatory[]
a| The operation type.
One of `create`, `merge`, `update` or `delete`.

[NOTE]
The `delete` operation is for **individual nodes** only.
It is not intended to run generic Cypher queries from JSON.

| properties
| label:Optional[] when operation is `delete`.
| The properties attached to the node.

| ids
| label:Optional[] when operation is `create`.
a|
Contains the primary/unique key properties that will be used to look up the entity.
In case you use `_elementId` (or `_id`) as a property name, it will use Neo4j's internal element id for the node lookup.

[WARNING]
If you use `_elementId` (or `_id`) with `merge` operations, it will behave as a simple update, i.e. if the node with the given element id does not exist, it will not be created.

| labels
| label:Optional[]
a| The labels attached to the node.

[NOTE]
Although Neo4j allows to create nodes without labels, it's not advised to do so from a performance perspective.

| type
| label:Mandatory[]
| The entity type: `node`.

| detach
| label:Optional[]
a| When operation is `delete`, you can specify whether to perform a link:{page-canonical-root}/cypher-manual/delete/["detach" delete].

[NOTE]
If no value is provided, the default is `false`.

|===

==== Examples

* An example of a `CREATE` operation;
+
[source,json]
----
{
  "type": "node",
  "op": "create",
  "labels": ["Foo", "Bar"],
  "properties": {
    "id": 1,
    "foo": "foo-value"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
CREATE (n:Foo:Bar) SET n = $properties
----
+
* An example of a `UPDATE` operation;
+
[source,json]
----
{
  "type": "node",
  "op": "update",
  "labels": ["Foo", "Bar"],
  "ids": {
    "id": 0
  },
  "properties": {
    "id": 1,
    "foo": "foo-value"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (n:Foo:Bar {id: $ids.id}) SET n += $properties
----
+
* An example of a `MERGE` operation;
+
[source,json]
----
{
  "type": "node",
  "op": "merge",
  "labels": ["Foo", "Bar"],
  "ids": {
    "id": 0
  },
  "properties": {
    "id": 1,
    "foo": "foo-value"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MERGE (n:Foo:Bar {id: $ids.id}) SET n += $properties
----
+
* An example of a `DELETE` operation;
+
[source,json]
----
{
  "type": "NODE",
  "op": "delete",
  "labels": ["Foo", "Bar"],
  "ids": {
    "id": 0
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (n:Foo:Bar {id: $ids.id}) DELETE n
----
+
* An example of a `DELETE` operation with detach `true`;
+
[source,json]
----
{
  "type": "NODE",
  "op": "delete",
  "labels": ["Foo", "Bar"],
  "ids": {
    "id": 0
  },
  "detach": true
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (n:Foo:Bar {id: $ids.id}) DETACH DELETE n
----

=== Relationship

Relationship format defines a set of fields which describes the operation (`create`, `update`, `merge` and `delete`), relationship type, source and target node references and properties.

[#table_cud_rels_fields]
.**Relationship format** fields
[cols="1,2,3",opts=header]
|===
| Field
| Mandatory
| Description

| op
| label:Mandatory[]
| The operation type. One of `create`, `merge`, `update` or `delete`.

| properties
| label:Optional[] when operation is `delete`.
| The properties attached to the relationship.

| rel_type
| label:Mandatory[]
| The relationship type.

|ids
| label:Optional[]
|Contains the primary/unique key properties that will be used to look up the relationship.

| from
| label:Mandatory[]
a| Contains information about the source node of the relationship.
`op` field can only be `merge` or `match` and by default it's `match`.
For the description of the `ids` and `labels` fields, please look at the node fields described <<table_cud_node_fields, above>>.

[NOTE]
If you use `_elementId` (or `_id`) field reference in `ids`, you can omit `labels` field.

| to
| label:Mandatory[]
a| Contains information about the target node of the relationship.
`op` field can only be `merge` or `match` and by default it's `match`.
For the description of the `ids` and `labels` fields, please look at the node fields described <<table_cud_node_fields, above>>.

[NOTE]
If you use `_elementId` (or `_id`) field reference in `ids`, you can omit `labels` field.

| type
| label:Mandatory[]
| The entity type: `relationship`.

|===

==== Examples

* An example of a `CREATE` operation;
+
[source,json]
----
{
  "type": "relationship",
  "op": "create",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    }
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    }
  },
  "properties": {
    "by": "incident"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (start:Foo {id: $from.ids.id}) WITH start
MATCH (end:Bar {id: $to.ids.id}) WITH start, end
CREATE (start)-[r:RELATED_TO]->(end)
SET r = $properties
----
+
* An example of a `CREATE` operation with `merging` the source node;
+
[source,json]
----
{
  "type": "relationship",
  "op": "create",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    },
    "op": "merge"
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    },
    "op": "match"
  },
  "properties": {
    "by": "incident"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MERGE (start:Foo {id: $from.ids.id}) WITH start
MATCH (end:Bar {id: $to.ids.id}) WITH start, end
CREATE (start)-[r:RELATED_TO]->(end)
SET r = $properties
----
+
* An example of a `UPDATE` operation;
+
[source,json]
----
{
  "type": "relationship",
  "op": "update",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    }
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    },
    "op": "merge"
  },
  "properties": {
    "by": "incident"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (start:Foo {id: $from.ids.id}) WITH start
MERGE (end:Bar {id: $to.ids.id}) WITH start, end
MATCH (start)-[r:RELATED_TO]->(end)
SET r += $properties
----
+
* An example of a `UPDATE` operation with `relationship ids`;
+
[source,json]
----
{
  "type": "relationship",
  "op": "update",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    }
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    },
    "op": "merge"
  },
  "ids": {
    "id": 5
  },
  "properties": {
    "by": "incident"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (start:Foo {id: $from.ids.id}) WITH start
MERGE (end:Bar {id: $to.ids.id}) WITH start, end
MATCH (start)-[r:RELATED_TO {id: $ids.id}]->(end)
SET r += $properties
----
+
* An example of a `MERGE` operation;
+
[source,json]
----
{
  "type": "relationship",
  "op": "merge",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    }
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    },
    "op": "merge"
  },
  "properties": {
    "by": "incident"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (start:Foo {id: $from.ids.id}) WITH start
MERGE (end:Bar {id: $to.ids.id}) WITH start, end
MERGE (start)-[r:RELATED_TO]->(end)
SET r += $properties
----
+
* An example of a `MERGE` operation with `relationship ids`;
+
[source,json]
----
{
  "type": "relationship",
  "op": "MERGE",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    }
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    },
    "op": "merge"
  },
  "ids": {
    "id": 5
  },
  "properties": {
    "by": "incident"
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (start:Foo {id: $from.ids.id}) WITH start
MERGE (end:Bar {id: to.ids.id}) WITH start, end
MERGE (start)-[r:RELATED_TO {id: $ids.id}]->(end)
SET r += $properties
----
+
* An example of a `DELETE` operation;
+
[source,json]
----
{
  "type": "relationship",
  "op": "delete",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    }
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    }
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (start:Foo {id: $from.ids.id}) WITH start
MATCH (end:Bar {id: $to.ids.id}) WITH start, end
MATCH (start)-[r:RELATED_TO]->(end)
DELETE r
----
+
* An example of a `DELETE` operation with `relationship ids`;
+
[source,json]
----
{
  "type": "relationship",
  "op": "DELETE",
  "rel_type": "RELATED_TO",
  "from": {
    "labels": ["Foo"],
    "ids": {
      "id": 0
    }
  },
  "to": {
    "labels": ["Bar"],
    "ids": {
      "id": 1
    }
  },
  "ids": {
    "id": 5
  }
}
----
+
which would be transformed into the following Cypher query:
+
[source,cypher]
----
MATCH (start:Foo {id: $from.ids.id}) WITH start
MATCH (end:Bar {id: $to.ids.id}) WITH start, end
MATCH (start)-[r:RELATED_TO {id: $ids.id}]->(end)
DELETE r
----