= Cypher Strategy

This strategy executes corresponding Cypher statements for each message received.

To configure a cypher strategy for a desired topic, you must follow the following convention:

[source,json,subs="verbatim,attributes"]
----
"neo4j.cypher.topic.<YOUR_TOPIC>": "<YOUR_CYPHER_QUERY>"
----

[IMPORTANT]
====
Starting with version 5.1.0 of the {product-name}, the Cypher strategy binds header, key, and value of the messages as `\__header`, `__key`, and `__value` respectively, which are passed to the user-provided Cypher query as predefined variables.
See xref:sink/configuration.adoc#cypher_strategy_settings[Cypher strategy settings] for more information on how to customize the name of the variables.

For backward compatibility, `event` is still available for use but will only correspond to the value of the message.
====

== Example

Given that you configure the topics your sink connector subscribes to within the sink configuration settings as follows;

[source,json]
----
  "topics": "creates,updates,deletes"
----

You need to declare that you want to use `cypher` strategy and provide the corresponding Cypher statement for each topic, similar to the following;

[source,json]
----
  "topics": "creates,updates,deletes",
  "neo4j.cypher.topic.creates": "WITH __value.event.state.after AS state MERGE (p:Person {name: state.properties.name, surname: state.properties.surname}) MERGE (f:Family {name: state.properties.surname}) MERGE (p)-[:BELONGS_TO]->(f)",
  "neo4j.cypher.topic.updates": "WITH __value.event.state.before AS before, __value.event.state.after AS after MATCH (p:Person {name: before.properties.name, surname: before.properties.surname}) MATCH (fPre:Family {name: before.properties.surname}) OPTIONAL MATCH (p)-[b:BELONGS_TO]->(fPre) DELETE b WITH after, p SET p.name = after.properties.name, p.surname = after.properties.surname MERGE (f:Family {name: after.properties.surname}) MERGE (p)-[:BELONGS_TO]->(f)",
  "neo4j.cypher.topic.deletes": "WITH __value.event.state.before AS before MATCH (p:Person {name: before.properties.name, surname: before.properties.surname}) DETACH DELETE p"
----

The above configuration excerpt defines that;

* messages received from `creates` topic will be unpacked by the Sink connector into Neo4j with the following Cypher query:
+
[source,cypher]
----
WITH __value.event.state.after AS state
MERGE (p:Person {name: state.properties.name, surname: state.properties.surname})
MERGE (f:Family {name: state.properties.surname})
MERGE (p)-[:BELONGS_TO]->(f)
----

* messages received from `updates` topic will be unpacked by the Sink connector into Neo4j with the following Cypher query:
+
[source,cypher]
----
WITH __value.event.state.before AS before, __value.event.state.after AS after
MATCH (p:Person {name: before.properties.name, surname: before.properties.surname})
MATCH (fPre:Family {name: before.properties.surname})
OPTIONAL MATCH (p)-[b:BELONGS_TO]->(fPre)
DELETE b
WITH after, p
SET p.name = after.properties.name, p.surname = after.properties.surname
MERGE (f:Family {name: after.properties.surname})
MERGE (p)-[:BELONGS_TO]->(f)
----

* messages received from `deletes` topic will be unpacked by the Sink connector into Neo4j with the following Cypher query:
+
[source,cypher]
----
WITH __value.event.state.before AS before
MATCH (p:Person {name: before.properties.name, surname: before.properties.surname})
DETACH DELETE p
----

== Creating the Sink instance

:strategy: cypher
include::partial$create-sink-instance.adoc[]

[NOTE]
====
Under the hood the connector will create a batch of changes for each topic, and will execute the query with a prepended `UNWIND` clause.
For the above example, the executed query for messages received from `creates` topic would look like;

[source,cypher]
----
UNWIND $events AS message
WITH message.value AS event, message.header AS __header, message.key AS __key, message.value AS __value
WITH __value.event.state.after AS state
MERGE (p:Person {name: state.properties.name, surname: state.properties.surname})
MERGE (f:Family {name: state.properties.surname})
MERGE (p)-[:BELONGS_TO]->(f)
----

where `$events` is a batch of change events.
====

== Batching of Cypher events

Starting from version 5.4.2, batched sink handlers are available for the Cypher strategy to provide better throughput when processing messages.
These handlers process messages in batches and apply them to the database more efficiently.

There are currently two batching strategies used by the Cypher sink handlers:

. APOC Core strategy: This strategy uses the `apoc.cypher.doIt` procedure to execute batches of the configured Cypher statement, one invocation per message in the batch.
. Native strategy: This strategy generates a single Cypher statement containing multiple subqueries for each message in the batch, and executes it using the standard Cypher execution engine.
The maximum number of subqueries included in a single batch when using the native strategy can be configured using the `neo4j.max-batched-queries` setting, which defaults to `50`.

The connector defaults to the APOC Core batching strategy when available, falling back to the native strategy when APOC Core is not available on the target database.

Batch size, which applies to both batching strategies, can be configured using the `neo4j.batch-size` setting, which defaults to `1000`.

== Exactly-once semantics

Starting from version 5.4.2, the Cypher sink handler can be configured to achieve exactly-once processing guarantees by keeping track of the last successfully processed message offset in the database.
This is achieved by storing a dedicated node representing the offset of the last successfully processed message.

Use the `neo4j.eos-offset-label` setting to specify a label name to attach to the offset node.
This setting is empty by default, meaning that exactly-once semantics are disabled and the connector will not keep track of processed message offsets in the target database, meaning that at-least-once processing guarantees are provided.

[IMPORTANT]
====
Make sure that the configured label has a node key constraint defined on the `strategy`, `topic` and `partition` node properties.

For example, if your `neo4j.eos-offset-label` is set to `__KafkaOffset`, the following constraint must appear on the target database:

[source,cypher]
----
CREATE CONSTRAINT kafka_offset_key IF NOT EXISTS FOR (n:__KafkaOffset) REQUIRE (n.strategy, n.topic, n.partition) IS NODE KEY
----
====