= Sink Monitoring
:type: sink

The Neo4j Connector for Kafka Sink provides JMX metrics for the xref:sink/cdc.adoc[Change Data Capture strategy] to help you monitor the status of the data ingestion process.

[IMPORTANT]
====
JMX metrics are not collected via the official Kafka Connect interface, and will not be reported by reporters defined via `metric.reporters` Kafka Connect setting.
To consume these metrics, you must use a JMX-compatible monitoring tool or agent.
====

== JMX Metrics label:new[Introduced in 5.3.0]

The following JMX metrics are available for CDC Sink connector instances:

* **ObjectName:** `kafka.connect:type=plugins,connector=+{CONNECTOR_NAME}+,task=+{TASK_ID}+`

[%width="100%",cols="m,a,a",opts=header]
|===
| Attribute | Type | Description

| `last_cdc_tx_commit_timestamp`
| Number
| The timestamp of the last committed CDC transaction pushed by the connector.

| `last_cdc_tx_start_timestamp`
| Number
| The timestamp of the start of the last CDC transaction pushed by the connector.

| `last_cdc_tx_id`
| Number
| The ID of the last CDC transaction pushed by the connector.
|===
