= Pattern strategy

This strategy allows you to extract nodes and relationships from a kafka message through extraction patterns.

== Configuration

To configure a pattern strategy for a desired topic, you must follow the following convention:

[source,json,subs="verbatim"]
----
"neo4j.pattern.topic.<YOUR_TOPIC>": "<PATTERN>"
----

For instance, given the following message published to the `user` and `lives_in` topics:

[source,json]
----
{"userId": 1, "name": "John", "surname": "Doe", "address": {"since": "2012-05", "city": "London", "country": "UK"}}
----

You can transform it into a node by providing the following configuration:

[source,json,subs="verbatim"]
----
"neo4j.pattern.topic.user": "(:User{!id: userId})"
----

You can also provide relationship patterns to transform it into a path, like `(n)-[r]->(m)`, by providing the following configuration:

[source,json,subs="verbatim"]
----
"neo4j.pattern.topic.lives_in": "(:User{!id: userId})-[:LIVES_IN{since}]->(:City{!name: address.city, !country: address.country})"
----

[NOTE]
Relationship key properties can only be used with Neo4j Enterprise Edition 5.7 and above, and AuraDB 5.

== Creating Sink instance

:strategy: pattern
include::partial$create-sink-instance.adoc[]

== Patterns

=== Node Patterns

Node patterns are defined similar to Cypher node patterns.

. Start with `(`.
. Define optional list of labels, separated by `:`, such as `:Person` or `:Person:Employee`.
. Open property section with `{`.
. Define properties to be treated as keys, each prepended with `!`, where at least one key property needs to be provided.
Individual message fields can be explicitly referenced and assigned to a user defined property in the format of `userId: \__key.user.id`.
By default, messages fields can be referenced as `__timestamp`, `\__headers`, `__key` and `__value`.
. Either;
.. Nothing or `*`, meaning that assign all properties from message to the node.
.. List of property names to be assigned to the node from message.
Individual message fields can be explicitly referenced and assigned to a user defined property in the format of `userName: \__value.user.name`.
By default, messages fields can be referenced as `__timestamp`, `\__headers`, `__key` and `__value`.
.. List of property names _not_ to be assigned to the node, each prepended with `-`, all other properties from message will be assigned to the node.
. Close property section with `}`.
. End with `)`.

[NOTE]
You cannot mix inclusion and exclusion inside patterns, i.e. your pattern must contain either all exclusion or inclusion properties.

==== Examples

* `MERGE` operation on `User` label with `userId` treated as a key and assigning all properties from incoming message value to the node
+
[source]
----
(:User{!userId})
----
+
or
+
[source]
----
(:User{!userId, *})
----

* `MERGE` operation on `User` label with `userId` treated as a key and assigning *only* `surname` property from incoming message to the node
+
[source]
----
(:User{!userId, surname})
----

* `MERGE` operation on `User` label with `userId` treated as a key and assigning *only* `surname` and `address.city` properties from incoming message to the node
+
[source]
----
(:User{!userId, surname, city: address.city})
----

* `MERGE` operation on `User` label with `userId` treated as key and assigning all properties excluding `address` property from incoming message to the node
+
[source]
----
(:User{!userId, -address})
----

* `MERGE` operation on `User` label with `userId` treated as key which will be taken from the key part of the message and assigning *only* `name` and `surname` properties from the value part of incoming message to the node
+
[source]
----
(:User{!userId: __key.id, name: __value.firstName, surname: __value.lastName})
----

* `MERGE` operation on `User` label with `userId` treated as key which will be taken from the key part of incoming message and assigning *only* `name`, `surname` properties from the value part, `createdBy` from the header and `createdAt` property as current timestamp to the node
+
[source]
----
(:User{!userId: __key.id, name: __value.firstName, surname: __value.lastName, createdBy: __header.username, createdAt: __timestamp})
----


=== Relationship Patterns

Relationship patterns are defined similar to Cypher relationship patterns.

. Node pattern for start node.
. `-[`
. Define relationship type, prepended by `:`, such as `:BOUGHT` or `:KNOWS`.
. Open property section with `{`.
. [Optional] Define properties to be treated as keys, each prepended with `!`, where at least one key property needs to be provided.
Individual message fields can be explicitly referenced and assigned to a user defined property in the format of `relationshipId: \__key.relationship.id`.
By default, messages fields can be referenced as `__timestamp`, `\__headers`, `__key` and `__value`.
. Either;
.. Nothing or `*`, meaning that assign all properties from message to the relationship.
.. List of property names to be assigned to the relationship from message.
Individual message fields can be explicitly referenced and assigned to a user defined property in the format of `relationshipType: \__value.relationship.type`.
By default, messages fields can be referenced as `__timestamp`, `\__headers`, `__key` and `__value`.
.. List of property names _not_ to be assigned to the relationship, each prepended with `-`, all other properties from message will be assigned to the relationship.
. Close property section with `}`.
. `]\->`
. Node pattern for end node.

[NOTE]
You cannot mix inclusion and exclusion inside patterns, i.e. your pattern must contains all exclusion or inclusion properties.

==== Examples

. `MERGE` operation on `User` and `Product` labels with `userId` and `productId` treated as keys respectively and `MERGE` a `BOUGHT` relationship between them assigning all other message properties to the relationship
+
[source]
----
(:User{!userId})-[:BOUGHT]->(:Product{!productId})
----

. `MERGE` operation on `User` and `Product` labels with `userId` and `productId` treated as keys respectively and `MERGE` a `BOUGHT` relationship between them assigning *only* `price` and `currency` properties from incoming message to the relationship
+
[source]
----
(:User{!userId})-[:BOUGHT{price,currency}]->(:Product{!productId})
----

. `MERGE` operation on `User` and `Product` labels with `userId` and `productId` treated as keys respectively and `MERGE` a `BOUGHT` relationship between them assigning *only* `price`,  `currency` and `shippingAddress.city` properties from incoming message to the relationship
+
[source]
----
(:User{!userId})-[:BOUGHT{price,currency,shippingAddress.city}]->(:Product{!productId})
----

. `MERGE` operation on `User` and `Product` labels with `userId` and `productId` treated as keys respectively and `MERGE` a `BOUGHT` relationship between them assigning all properties *excluding* `shippingAddress` from incoming message to the relationship
+
[source]
----
(:User{!userId})-[:BOUGHT{-shippingAddress}]->(:Product{!productId})
----

. `MERGE` operation on `User` and `Product` labels with `userId` and `productId` treated as keys respectively, assign `userFirstName` and `userLastName` properties from the message to the `User` node and `MERGE` a `BOUGHT` relationship between them assigning *only* `price` and `currency` properties from the message to the relationship
+
[source]
----
(:User{!userId, userFirstName, userLastName})-[:BOUGHT{price, currency}]->(:Product{!productId})
----

. `MERGE` operation on `User` and `Product` labels with `userId` and `productId` treated as keys respectively and `MERGE` a `BOUGHT` relationship between them assigning *only* `transactionId` property as a key property from key part of the message and `date` from value part of the message to the relationship
+
[source]
----
(:User{!userId})-[:BOUGHT{!transactionId: __key.transaction.id, date: __value.transaction.date}]->(:Product{!productId})
----


== Tombstone records

The pattern strategy supports https://en.wikipedia.org/wiki/Tombstone_(data_store)[tombstone records].
In order to use it, message key should contain at least the key properties present in the provided pattern and message value should be set as `null`.

[IMPORTANT]
It is not possible to define multiple patterns for a single topic, such as extracting more than one node or relationship type from a single message.
In order to achieve this, you have to use a different topic for each pattern.

== Batching of pattern events

Starting from version 5.4.0, batched sink handlers are available for the Pattern strategy to provide better throughput when processing pattern events.
These handlers process messages in batches and apply them to the database more efficiently.

There are currently two batching strategies used by the pattern sink handlers:

. APOC Core based strategy: This strategy uses the `apoc.cypher.doIt` procedure to execute batches of Cypher statements generated from the pattern events.
. Native strategy: This strategy generates a single Cypher statement containing multiple subqueries for each message in the batch, and executes it using the standard Cypher execution engine.
The maximum number of subqueries included in a single batch when using the native strategy can be configured using the `neo4j.max-batched-queries` setting, which defaults to `50`.

Connector prefers APOC Core `apoc.cypher.doIt` based batching strategy when available, falling back to the native strategy when APOC Core is not available on the target database.

Batch size, which applies to both batching strategies, can be configured using the `neo4j.batch-size` setting, which defaults to `1000`.

== Exactly-once semantics

Starting from version 5.4.0, pattern sink handlers can be configured to achieve exactly-once processing guarantees by keeping track of the last successfully processed message offset in the database.
This is achieved by storing a dedicated node representing the offset of the last successfully processed message.
Use `neo4j.eos-offset-label` setting to specify a label name to attach to the offset node.
This setting is empty by default, meaning that exactly-once semantics are disabled and the connector will not keep track of processed message offsets in the target database, meaning that at-least-once processing guarantees are provided.

[IMPORTANT]
====
Make sure that the configured label has a NODE KEY constraint defined on the 'strategy', 'topic' and 'partition' properties.

Assuming your `neo4j.eos-offset-label` is set to `__KafkaOffset`, the following constraint should be created on the target database:

[source,cypher]
----
CREATE CONSTRAINT kafka_offset_key IF NOT EXISTS FOR (n:__KafkaOffset) REQUIRE (n.strategy, n.topic, n.partition) IS NODE KEY
----
====
