= Installation
:page-aliases: kafka-connect/installation.adoc

[#distribution]
== Distribution

The latest version of the connector is {exact-connector-version}.

[#confluent-dist]
=== Neo4j Connector for Confluent

This package can be deployed to Confluent Platform as a self-managed connector, and to Confluent Cloud as a custom connector.

The package is available for download from link:{url-confluent-hub-neo4j}[Confluent Hub] or from the link:{url-github}/releases/download/{exact-connector-version}/neo4j-kafka-connect-{exact-connector-version}.zip[GitHub repository].

[#kafka-dist]
=== Neo4j Connector for OSS Apache Kafka

This package can be deployed to any Apache Kafka distribution running Apache Kafka Connect, including Amazon Managed Streaming for Apache Kafka (Amazon MSK).

The package is available for download from the link:{url-github}/releases/download/{exact-connector-version}/neo4j-kafka-connect-{exact-connector-version}.jar[GitHub repository].

== Installation

The {product-name} is a plugin designed to run in an Apache Kafka Connect environment, which is deployed separately from the Neo4j database.

For standalone Kafka Connect installations, download the <<kafka-dist, self-contained JAR file>> and copy it into the `plugins` directory for each of your Kafka Connect cluster members.
