= Usage with a Neo4j cluster

ifdef::env-docs[]
[abstract]
--
This chapter describes considerations around using Neo4j Streams with Neo4j Enterprise Causal Cluster.
--
endif::env-docs[]

[[cluster_overview]]
== Overview

link:https://neo4j.com/docs/operations-manual/current/clustering/[Neo4j Clustering] is a feature available in
Enterprise Edition which allows high availability of the database.

When the {product-name} is used with a Neo4j cluster, the most important consideration is to use
a routing driver. Generally, routing drivers are identified by a URI starting with `neo4j://` as the scheme instead of just `bolt://`.

If your Neo4j cluster is located at `graph.mycompany.com:7687`, simply configure the Kafka Connect worker with the following:

[source,ini]
----
neo4j.server.uri=neo4j://graph.mycompany.com:7687
----

The use of the `neo4j` driver will mean that the Neo4j Driver itself will handle connecting to
the correct cluster member, and managing changes to the cluster membership over time.

For further information on routing drivers, see the link:https://neo4j.com/docs/java-manual/current/[Neo4j Driver Manual].
