[[streams-migration]]
= Migrate from Neo4j Streams

The Neo4j Connector for Kafka and the link:https://neo4j.com/docs/kafka-streams/[Neo4j Streams plugin] differ significantly in the architecture.

The following table summarises the differences between the two solutions.

[cols="1s,1,1",options="header"]
|===
| | Neo4j Streams plugin | Neo4j Connector for Kafka

|Deployment
|Plugin deployed on Neo4j as JAR file; manages Kafka connections itself
|Kafka Connect connector running on Kafka Connect, running separately from Neo4j

|Communication
|In-process client for the underlying Neo4j database
|Establishes a database connection over BOLT using the Neo4j Driver for Java

|Configuration
|Kafka configuration options in the _neo4j.conf_ file
|Kafka configuration and link:https://docs.confluent.io/platform/current/connect/index.html#converters[Converters] configured either globally in the Kafka Connect instance or per connector in the connector's configuration

|Sink/Source role
|Supports both sink and source capabilities within a single plugin instance
|Must be configured explicitly as a source or sink connector at launch

|===

== Kafka configuration

=== Near-equivalent settings

The following Kafka settings managed in the Streams plugin have a near-equivalent setting in the Neo4j Connector.

[source]
----
neo4j.batch-size
neo4j.query.timeout
----

=== Deprecated settings

The following _neo4j.conf_ settings, previously referenced in the link:https://neo4j.com/docs/kafka-streams/[Neo4j Streams documentation], are no longer supported and should not be included in the new connector configuration.

[NOTE]
====
In general, configuration settings starting with the `kafka.` prefix are no longer supported in the Kafka connector.
====

.General plugin settings
[source]
----
streams.procedures.enabled
streams.sink.enabled
streams.source.enabled
----

.Consumer settings
[source]
----
kafka.auto.offset.reset
kafka.enable.auto.commit
kafka.group.id
kafka.max.poll.records
kafka.session.timeout.ms
kafka.topic.discovery.polling.interval
kafka.value.deserializer
kafka.value.deserializer
----

.Producer settings
[source]
----
kafka.acks
kafka.batch.size
kafka.buffer.memory
kafka.linger.ms
kafka.retries
kafka.transactional.id
----

.Security and connection settings
[source]
----
kafka.bootstrap.servers
kafka.connection.timeout.ms
kafka.security.protocol
kafka.ssl.endpoint.identification.algorithm
kafka.ssl.key.password
kafka.ssl.keystore.location
kafka.ssl.keystore.password
kafka.ssl.truststore.location
kafka.ssl.truststore.password
----

.Other settings
[source]
----
kafka.reindex.batch.size
kafka.replication
kafka.streams.log.compaction.strategy
----

== Streams as a Source

If you are using the Streams connector as a source, then read link:https://neo4j.com/docs/kafka/current/source.
Streams as a source has been superseded by the CDC + Neo4j Connector for Kafka Source connector, and you will need to be on a Neo4j 5.26 LTS enterprise edition, the latest calver Enterprise Edition, Aura Business Critical, or Virtual Private Connect tiers in order to use CDC.

The following source configuration settings are no longer in use:

[source]
----
streams.source.enabled=true | false
streams.source.enabled.from.<database>=true | false
streams.source.topic.relationships.<TOPIC_NAME>.key_strategy=default
streams.source.schema.polling.interval=10000
----

The following streams' source configuration settings have a near equivalent:

[source]
----
streams.source.topic.nodes.<TOPIC_NAME>=<PATTERN> 
streams.source.topic.relationships.<TOPIC_NAME>=<PATTERN>
----

The pattern syntax used for the Streams plugin has been slightly updated to better reflect Cypher pattern syntax.
Refer to the link:https://neo4j.com/docs/kafka/current/source/cdc/#patterns[Patterns section] for more information about the new syntax.
After you've migrated your patterns to the new syntax, follow the instructions in the link:https://neo4j.com/docs/kafka/current/source/cdc/#_configuration[Configuration section] to build your new configuration.

For example, the following Streams configuration:

[source]
----
streams.source.topic.nodes.my-nodes-topic=Person{*}
streams.source.topic.relationships.my-rels-topic=BELONGS-TO{*}
----

Will become:

[source]
----
"neo4j.source-strategy": "CDC",
"neo4j.cdc.topic.my-nodes-topic.patterns": "(:Person)"
"neo4j.cdc.topic.my-rels-topic.patterns": "()-[:BELONGS-TO]->()"
----

[NOTE]
====
If you are on a Neo4j or Aura version where CDC is not available, you can use the query-based source connector instead.
Refer to the link:https://neo4j.com/docs/kafka/current/source/query/[Query strategy section] for more information.
====

== Streams as a Sink

If you are using the Streams connector as a sink, then read link:https://neo4j.com/docs/kafka/current/sink/[Sink configuration section].

Neo4j Connector for Kafka supports all of the sink strategies available in the Streams plugin.

=== Cypher strategy

The Streams setting

[source]
----
streams.sink.topic.cypher.<TOPIC_NAME>=<CYPHER_QUERY>
----

becomes:

[source]
----
"neo4j.cypher.topic.<YOUR_TOPIC>": "<YOUR_CYPHER_QUERY>"
----

in the Neo4j Connector for Kafka. Furthermore, you have more options to map incoming message headers, keys, and/or values in recent versions, as described link:https://neo4j.com/docs/kafka/current/sink/cypher/[here].

=== Change Data Capture Event strategy

Both SourceId and Schema strategies for CDC events are still supported. While Neo4j Connector for Kafka Source CDC connectors will emit CDC events with a new CDC-compatible schema, sink connectors are still able to read CDC messages generated from the Streams plugin.

The following SourceId Streams configuration:

[source]
----
streams.sink.topic.cdc.sourceId=<list of topics separated by semicolon>
streams.sink.topic.cdc.sourceId.labelName=<the label attached to the node, default=SourceEvent>
streams.sink.topic.cdc.sourceId.idName=<the id name given to the CDC id field, default=sourceId>
----

Will become:

[source]
----
"neo4j.cdc.source-id.topics": "<comma-separated list of topics>"
"neo4j.cdc.source-id.label-name": "<the label attached to the node, default=SourceEvent>"
"neo4j.cdc.source-id.property-name": "<the property name given to the CDC id field, default=sourceId>"
----

Similar to above, the following Schema Streams configuration:

[source]
----
streams.sink.topic.cdc.schema=<LIST_OF_TOPICS_SEPARATED_BY_SEMICOLON>
----

Will become:
[source]
----
"neo4j.cdc.schema.topics": "<COMMA_SEPARATED_LIST_OF_TOPICS>"
----

=== Pattern strategy

The pattern syntax in Streams configuration is fully supported in Neo4j Connector for Kafka. While both simple and Cypher-like patterns are supported, Cypher-like patterns are the more preferred way of defining patterns.

The following pattern Streams configuration:

[source]
----
streams.sink.topic.pattern.node.user=(:User{!userId})
streams.sink.topic.pattern.node.product=(:Product{!productId})
streams.sink.topic.pattern.relationship.bought=(:User{!userId})-[:BOUGHT{price, currency}]->(:Product{!productId})
----

Will become:

[source]
----
"neo4j.pattern.topic.user": "(:User{!userId})",
"neo4j.pattern.topic.product": "(:Product{!productId})",
"neo4j.pattern.topic.bought": "(:User{!userId})-[:BOUGHT{price, currency}]->(:Product{!productId})"
----

Note that there is no node or relationship distinction in Neo4j Connector for Kafka while declaring your pattern configuration. You can also add more topics with different patterns to the same connector. Furthermore, Neo4j Connector for Kafka introduces additional capabilities in your patterns, such as mapping incoming message properties to a new name, as discussed in the link:https://neo4j.com/docs/kafka/current/sink/pattern/#_patterns[Patterns section].

=== CUD File Format strategy

The CUD File Format strategy in Streams configuration is fully supported in Neo4j Connector for Kafka.

The following Streams plugin configuration:

[source]
----
streams.sink.topic.cud=<LIST_OF_TOPICS_SEPARATED_BY_SEMICOLON>
----

Will become:

[source]
----
"neo4j.cud.topics": "<COMMA_SEPARATED_LIST_OF_TOPICS>"
----

=== Error handling

Kafka Connect has its own error-handling mechanism for processing sink messages.
Refer to the link:https://neo4j.com/docs/kafka/current/sink/error-handling/[Error handling section] for more information on configuring your sink connectors for advanced error handling.