[[streams-migration]]
= Migrate from Neo4j Streams

There are significant differences between the Neo4j Streams plugin (referred to as the Streams plugin), which runs on Neo4j as a plugin, and the Neo4j Connector for Kafka (referred to as the Connector for Kafka), which runs on Kafka Connect.

This guide has been provided to help you understand which Streams plugin settings have near equivalents to those available in the Kafka Connector, and which settings do not apply. Please refer to the Neo4j Connector for Kafka documentation to understand the behavioural differences and successfully configure the connector.

== Architectural differences

Streams runs as a plugin (jar), deployed on Neo4j, and configured via _neo4j.conf_ file. The streams plugin manages Kafka connections itself, hence it needs several configuration options to configure the underlying Kafka clients accordingly.

Neo4j Connector for Kafka is a Kafka Connect connector (JAR) that runs on top of Kafka Connect. Kafka Connect must be configured and brought online separately before deploying the Connector for Kafka. Please note that Kafka Connect introduces the concept of link:https://docs.confluent.io/platform/current/connect/index.html#converters[Converters], and you will need to configure them either globally for all your connectors in your Kafka Connect instance or per connector in the connector's configuration. 

The Streams plugin supports both sink and source capabilities within a single plugin instance, whereas the Neo4j Connector for Kafka must be configured explicitly as a source or sink connector at launch.

Unlike the Streams plugin, the Neo4j Connector for Kafka does not handle Kafka-specific configuration settings. Please ensure the appropriate settings are set on Kafka Connect. 

The Streams plugin operates as an in-process client for the underlying Neo4j database, whereas Neo4j Connector for Kafka is designed to run on Kafka Connect and establishes a database connection over BOLT using the Neo4j Driver for Java.

The following settings are no longer required within the Neo4j Connector for Kafka.

[source]
----
streams.procedures.enabled=true | false <1>
streams.sink.enabled=true
streams.source.enabled=true
----
<1> The default is `true`.

== Kafka settings

The following settings were previously referenced in the Streams documentation; they may have been in the _neo4j.conf_ file, they are no longer supported and should not be included in the new connector configuration. Please ensure your Kafka Connect instance is configured correctly. Please refer to link:https://docs.confluent.io/platform/current/connect/index.html[Confluent] or link:https://kafka.apache.org/42/kafka-connect/overview/[Apache Kafka] documentation for details.

NOTE: These settings are listed for reference and should not be used for your Kafka Connect instance. Please refer to the relevant documentation for configuring a Kafka Connect instance instead. 

=== Consumer settings

Control how your application reads data from Kafka.

[source]
----
kafka.auto.offset.reset=earliest
kafka.enable.auto.commit=true | false
kafka.group.id=
kafka.max.poll.records=500 <1>
kafka.session.timeout.ms=15000
kafka.topic.discovery.polling.interval=300000
kafka.value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer <2>
kafka.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer <3>
----
<1> `500` is the default value.
<2> Common for Schema Registry.
<3> Standard raw bytes.

=== Producer settings

These control how your application sends data to Kafka.

[source]
----
kafka.acks=1all
kafka.batch.size=16384
kafka.buffer.memory=33554432
kafka.linger.ms=1
kafka.retries=2
kafka.transactional.id=
----

=== Security and connection settings

General settings for establishing and securing the connection to the cluster.

[source]
----
kafka.bootstrap.servers=
kafka.connection.timeout.ms=10000
kafka.security.protocol=SSL
kafka.ssl.endpoint.identification.algorithm=HTTPS
kafka.ssl.key.password=
kafka.ssl.keystore.location=
kafka.ssl.keystore.password=
kafka.ssl.truststore.location=
kafka.ssl.truststore.password=
----

=== Miscellaneous / Stream settings

[source]
----
kafka.reindex.batch.size=1000
kafka.replication=1
kafka.streams.log.compaction.strategy=delete
----

=== Configuring Kafka and Neo4j to work together

The following Kafka settings managed in the Streams plugin have a near equivalent setting in the Neo4j Connector that should be reviewed.

[source]
----
neo4j.batch-size=1000
neo4j.query.timeout=0
----

== Streams as a Source

If you are using the Streams connector as a source, then read https://neo4j.com/docs/kafka/current/source. Streams as a source has been superseded by the CDC + Neo4j Connector for Kafka Source connector, and you will need to be on a Neo4j 5.26 LTS enterprise edition, the latest calver Enterprise Edition, Aura Business Critical, or Virtual Private Connect tiers in order to use CDC.

The following source configuration settings are no longer in use:

[source]
----
streams.source.enabled=true | false
streams.source.enabled.from.<database>=true | false
streams.source.topic.relationships.<TOPIC_NAME>.key_strategy=default
streams.source.schema.polling.interval=10000
----

The following streams' source configuration settings have a near equivalent:

[source]
----
streams.source.topic.nodes.<TOPIC_NAME>=<PATTERN> 
streams.source.topic.relationships.<TOPIC_NAME>=<PATTERN>
----

The pattern syntax used for the Streams plugin has been slightly updated to better reflect Cypher pattern syntax. Please refer to the link:https://neo4j.com/docs/kafka/current/source/cdc/#patterns[Patterns section] for more information about the new syntax. After you've migrated your patterns to the new syntax, please follow the instructions in the link:https://neo4j.com/docs/kafka/current/source/cdc/#_configuration[Configuration section] to build your new configuration.

For example, the following Streams configuration:

[source]
----
streams.source.topic.nodes.my-nodes-topic=Person{*}
streams.source.topic.relationships.my-rels-topic=BELONGS-TO{*}
----

Will become:

[source]
----
"neo4j.source-strategy": "CDC",
"neo4j.cdc.topic.my-nodes-topic.patterns": "(:Person)"
"neo4j.cdc.topic.my-rels-topic.patterns": "()-[:BELONGS-TO]->()"
----

[NOTE]
====
If you are on a Neo4j or Aura version where CDC is not available, you can use the query-based source connector instead.
Please refer to the link:https://neo4j.com/docs/kafka/current/source/query/[Query strategy section] for more information.
====

== Streams as a Sink

If you are using the Streams connector as a sink, then read link:https://neo4j.com/docs/kafka/current/sink/[Sink configuration section].

Neo4j Connector for Kafka supports all of the sink strategies available in the Streams plugin.

=== Cypher strategy

The Streams setting

[source]
----
streams.sink.topic.cypher.<TOPIC_NAME>=<CYPHER_QUERY>
----

becomes:

[source]
----
"neo4j.cypher.topic.<YOUR_TOPIC>": "<YOUR_CYPHER_QUERY>"
----

in the Neo4j Connector for Kafka. Furthermore, you have more options to map incoming message headers, keys, and/or values in recent versions, as described link:https://neo4j.com/docs/kafka/current/sink/cypher/[here].

=== Change Data Capture Event strategy

Both SourceId and Schema strategies for CDC events are still supported. While Neo4j Connector for Kafka Source CDC connectors will emit CDC events with a new CDC-compatible schema, sink connectors are still able to read CDC messages generated from the Streams plugin.

The following SourceId Streams configuration:

[source]
----
streams.sink.topic.cdc.sourceId=<list of topics separated by semicolon>
streams.sink.topic.cdc.sourceId.labelName=<the label attached to the node, default=SourceEvent>
streams.sink.topic.cdc.sourceId.idName=<the id name given to the CDC id field, default=sourceId>
----

Will become:

[source]
----
"neo4j.cdc.source-id.topics": "<comma-separated list of topics>"
"neo4j.cdc.source-id.label-name": "<the label attached to the node, default=SourceEvent>"
"neo4j.cdc.source-id.property-name": "<the property name given to the CDC id field, default=sourceId>"
----

Similar to above, the following Schema Streams configuration:

[source]
----
streams.sink.topic.cdc.schema=<LIST_OF_TOPICS_SEPARATED_BY_SEMICOLON>
----

Will become:
[source]
----
"neo4j.cdc.schema.topics": "<COMMA_SEPARATED_LIST_OF_TOPICS>"
----

=== Pattern strategy

The pattern syntax in Streams configuration is fully supported in Neo4j Connector for Kafka. While both simple and Cypher-like patterns are supported, Cypher-like patterns are the more preferred way of defining patterns.

The following pattern Streams configuration:

[source]
----
streams.sink.topic.pattern.node.user=(:User{!userId})
streams.sink.topic.pattern.node.product=(:Product{!productId})
streams.sink.topic.pattern.relationship.bought=(:User{!userId})-[:BOUGHT{price, currency}]->(:Product{!productId})
----

Will become:

[source]
----
"neo4j.pattern.topic.user": "(:User{!userId})",
"neo4j.pattern.topic.product": "(:Product{!productId})",
"neo4j.pattern.topic.bought": "(:User{!userId})-[:BOUGHT{price, currency}]->(:Product{!productId})"
----

Note that there is no node or relationship distinction in Neo4j Connector for Kafka while declaring your pattern configuration. You can also add more topics with different patterns to the same connector. Furthermore, Neo4j Connector for Kafka introduces additional capabilities in your patterns, such as mapping incoming message properties to a new name, as discussed in the link:https://neo4j.com/docs/kafka/current/sink/pattern/#_patterns[Patterns section].

=== CUD File Format strategy

The CUD File Format strategy in Streams configuration is fully supported in Neo4j Connector for Kafka.

The following Streams plugin configuration:

[source]
----
streams.sink.topic.cud=<LIST_OF_TOPICS_SEPARATED_BY_SEMICOLON>
----

Will become:

[source]
----
"neo4j.cud.topics": "<COMMA_SEPARATED_LIST_OF_TOPICS>"
----

=== Error handling

Kafka Connect has its own error-handling mechanism for processing sink messages.
Please refer to the link:https://neo4j.com/docs/kafka/current/sink/error-handling/[Error handling section] for more information on configuring your sink connectors for advanced error handling.