[[connector-migration]]
= Migrate from 5.0 to 5.1+

[NOTE]
====
Migration is required when moving *from 5.0.x* to any later release (for example 5.1.x or 5.3.x), because 5.0.x uses a different configuration schema.
The configuration schema introduced in 5.1 is still current, so this guide applies regardless of which later version you migrate to.

Moving between 5.1.x and later 5.x releases (through 5.4) is an in-place upgrade and does not require configuration migration.
For generic plugin upgrade steps, see https://docs.confluent.io/platform/current/connect/upgrade.html[Confluent Documentation -> Upgrade a Connector Plugin].
====

When migrating the {product-name} from 5.0 to 5.1 or later, be aware that many of the configuration properties have been changed and updated.
Read over xref:whats-new.adoc[] to familiarize with these changes, and make sure that the new configuration logically matches the previous configuration.

IMPORTANT: Connector *MUST* be at version 5.0.6 before following the migration guides as it includes a configuration conversion helper to make the upgrade easier.

== Migration guides

Follow the relevant instructions to configure and deploy the new connector.

* Read the xref:migration/5.1/migration-docker.adoc[Confluent Platform migration] for a connector deployed to Confluent Platform as a self-managed connector.
* Read the xref:migration/5.1/migration-confluent-cloud.adoc[Confluent Cloud migration] for a connector deployed as a Custom Connector on Confluent Cloud.

== Troubleshooting

[qanda]
Failing to connect to Neo4j instance?::
The configuration migration process does not migrate the password of the Neo4j instance or other sensitive properties.
You need to enter these properties again.
Once updated, restart the connector.

Unexpected error::
Looking at the logs of Kafka Connect may reveal other errors in configuration.
. On Confluent Cloud, the logs are accessible through the *Logs* section on the Connector run page.
. On Confluent Platform, the logs are accessible through the Docker command `docker-compose logs -f connect`.