[[connector-migration]]
= Migrate from 5.0 to 5.1

When upgrading the {product-name} to 5.1, be aware that many of the configuration properties have been changed and updated.
Read over xref:whats-new.adoc[] to familiarize with the recent changes, and make sure that the new configuration logically matches the previous configuration.

For generic Kafka Connect plugin upgrade documentation see: https://docs.confluent.io/platform/current/connect/upgrade.html[Confluent Documentation -> Upgrade a Connector Plugin].

IMPORTANT: Connector *MUST* be at version 5.0.6 before following the migration guides as it includes a configuration conversion helper to make the upgrade easier.

== Migration guides

Follow the relevant instructions to configure and deploy the new connector.

* Read the xref:migration/5.1/migration-docker.adoc[Confluent Platform migration] for a connector deployed to Confluent Platform as a self-managed connector.
* Read the xref:migration/5.1/migration-confluent-cloud.adoc[Confluent Cloud migration] for a connector deployed as a Custom Connector on Confluent Cloud.

== Troubleshooting

[qanda]
Failing to connect to Neo4j instance?::
The configuration migration process does not migrate the password of the Neo4j instance or other sensitive properties.
You need to enter these properties again.
Once updated, restart the connector.

Unexpected error::
Looking at the logs of Kafka Connect may reveal other errors in configuration.
. On Confluent Cloud, the logs are accessible through the *Logs* section on the Connector run page.
. On Confluent Platform, the logs are accessible through the Docker command `docker-compose logs -f connect`.