[[connector-migration]]
= 5.0.x => 5.1 Migration Guide

When upgrading to the new {connector-version} {product-name} be aware that many of the configuration properties have been changed and updated.
Please take special care to ensure the new configuration logically matches the previous configuration.

Firstly, read over xref:whats-new.adoc[] to get familiarised with the recent changes.

For generic Kafka Connect plugin upgrade documentation see: https://docs.confluent.io/platform/current/connect/upgrade.html[Confluent Documentation -> Upgrade a Connector Plugin]

== Deployment guides

Depending on how the Plugin is deployed follow the relevant guide:

xref:migration/5.1/migration-docker.adoc[Confluent Platform Migration]::
Deployed to Confluent Platform as a self-managed connector
xref:migration/5.1/migration-confluent-cloud.adoc[Confluent Cloud Migration]::
Deployed as a Custom Connector on Confluent Cloud

== Troubleshooting

[qanda]
Failing to connect to Neo4j instance?::
The configuration migration login does not migrate the password of the Neo4j instance or other sensitive properties.
These options need to be re-entered. Once updated re-run the connector.

Unexpected error::
Looking at the logs of Kafka Connect may reveal other errors in configuration.
. Confluent Cloud
.. Logs are accessible through the `Logs` section on the Connector run page
. Confluent Platform
.. Logs are accessible through docker commands `docker-compose logs -f connect`