=== Change Data Capture Event Strategy

[IMPORTANT]
Change Data Capture Event Strategy currently does not support Change Data Capture feature provided with Neo4j Enterprise and Aura Enterprise.
Support for this will be added in upcoming releases of the connector.

This strategy allows to ingest CDC events coming from another Neo4j instance, that generates change events based on neo4j streams plugin.
There are two sub-strategies that can be used;

* SourceId
+
This strategy merges nodes and relationships by the CDC event `id` field (it's related to the Neo4j physical ID).

* Schema
+
This strategy merges nodes and relationships by the constraints (UNIQUENESS, NODE_KEY) defined in the source database.

==== SourceId sub-strategy

`SourceId` strategy merges nodes and relationships by the source entity's `id` values, by storing this value as an explicit property on the target node and by marking nodes with an explicit label.

Configuration of this strategy requires declaration of list of topics to read change events from, and optional label name to be used as a marker and also the property name to store the `id` values of the source entities.

[source,json,subs="verbatim,attributes"]
----
"neo4j.topic.cdc.sourceId": "<list of topics separated by semicolon>"
"neo4j.topic.cdc.sourceId.labelName": "<the label attached to the node, default=SourceEvent>"
"neo4j.topic.cdc.sourceId.idName": "<the id name given to the CDC id field, default=sourceId>"
----

==== Example

Given that you configure the topics your sink connector subscribes to within the sink configuration settings as follows;

[source,json]
----
"topics": "topic.1,topic.2"
----

You need to declare that you want to use `cdc.sourceId` strategy by providing the list of topics you want to consume change events from.

[source,json,subs="verbatim,attributes"]
----
"neo4j.topic.cdc.sourceId": "topic.1;topic.2"
----

Each streams change event will then be projected into a graph entity, for instance the following event:

[source,json]
----
include::ROOT:example$producer-data/node.created.json[]
----

will be persisted as the following node:

[source,cypher]
----
(:Person:SourceEvent {first_name: "Anne Marie", last_name: "Kretchmar", email: "annek@noanswer.org", sourceId: "1004"})
----

==== Schema sub-strategy

`Schema` strategy merges nodes and relationships by the constraints declared in the change event, thus preserves the source schema structure.

Configuration of this strategy requires declaration of list of topics to read change events from.

[source,json,subs="verbatim,attributes"]
----
"{environment}.topic.cdc.schema": "<LIST_OF_TOPICS_SEPARATED_BY_SEMICOLON>"
----

==== Example

Given that you configure the topics your sink connector subscribes to within the sink configuration settings as follows;

[source,json]
----
"topics": "topic.1,topic.2"
----

You need to declare that you want to use `cdc.schema` strategy by providing the list of topics you want to consume change events from.

[source,json,subs="verbatim,attributes"]
----
"{environment}.topic.cdc.schema": "topic.1;topic.2"
----

Each streams change event will then be projected into a graph entity.

For instance the following node creation event:

[source,json]
----
include::ROOT:example$producer-data/node.created.json[]
----

will be persisted as the following node:

[source,cypher]
----
(:Person {first_name: "Anne Marie", last_name: "Kretchmar", email: "annek@noanswer.org"})
----

where the sink connector will use the `schema` field in order to insert/update the nodes, without a need for extra properties or labels.

In case of relationship, the following relationship creation event:

[source,json]
----
include::ROOT:example$producer-data/relationship.created.json[]
----

wll be persisted as the following relationship:

[source,cypher]
----
(:Person {last_name: "Santurbano", first_name: "Andrea"})-[:KNOWS {since: "2018-04-05T12:34:00[Europe/Berlin]"}]->(:Person {last_name: "Hunger", first_name: "Michael"})
----

where the sink connector will use the `ids` fields of the start & end nodes of the change event to create or update the relationship, again without a need for extra properties or labels.
