=== Change Data Capture Event Strategy

This method allows to ingest CDC events coming from another Neo4j Instance. You can use two sub strategies:

* The `SourceId` sub-strategy which merges the nodes/relationships by the CDC event `id` field (it's related to the Neo4j physical ID)
* The `Schema` sub-strategy which merges the nodes/relationships by the constraints (UNIQUENESS, NODE_KEY) defined in your graph model

==== The `SourceId` sub-strategy

You can configure the topic in the following way:

[source,json,subs="verbatim,attributes"]
----
"{environment}.topic.cdc.sourceId": "<list of topics separated by semicolon>"
"{environment}.topic.cdc.sourceId.labelName": "<the label attached to the node, default=SourceEvent>"
"{environment}.topic.cdc.sourceId.idName": "<the id name given to the CDC id field, default=sourceId>"
----

[source,json,subs="verbatim,attributes"]
----
"{environment}.topic.cdc.sourceId": "my-topic;my-other.topic"
----

Each streams event will be projected into the related graph entity, for instance the following event:

[source,json]
----
include::ROOT:example$producer-data/node.created.json[]
----

will be persisted as the following node:

[source,cypher]
----
Person:SourceEvent{first_name: "Anne Marie", last_name: "Kretchmar", email: "annek@noanswer.org", sourceId: "1004"}
----

as you can notice, ingested event has been projected with two peculiarities:

* the `id` field has transformed into `sourceId`;
* the node has an additional label `SourceEvent`;

these two fields will be used in order to match the node/relationship for future updates/deletes

==== The `Schema` sub-strategy

You can configure the topic in the following way:

[source,json,subs="verbatim,attributes"]
----
"{environment}.topic.cdc.schema": "<LIST_OF_TOPICS_SEPARATED_BY_SEMICOLON>"
----

[source,json,subs="verbatim,attributes"]
----
"{environment}.topic.cdc.schema": "my-topic;my-other.topic"
----

Each streams event will be projected into the related graph entity, for instance the following event:

[source,json]
----
include::ROOT:example$producer-data/node.created.json[]
----

will be persisted as the following node:

[source,cypher]
----
Person{first_name: "Anne Marie", last_name: "Kretchmar", email: "annek@noanswer.org"}
----

The `Schema` sub-strategy leverages the `schema` field in order to insert/update the nodes so no extra fields will be created.

In case of relationship

[source,json]
----
include::ROOT:example$producer-data/relationship.created.json[]
----

the `Schema` sub-strategy leverages the `ids` fields in order to insert/update the relationships so no extra fields will be created.
